apiVersion: v1
entries:
  byoc:
  - apiVersion: v2
    created: "2019-12-05T15:55:05.320079+01:00"
    description: Deploy any container in Okteto
    digest: 343c4095de92eb1a3542a6ded94242eaa5af2ee11b31de00057efeaf56c6abf8
    home: https://github.com/rberrelleza/byoc
    icon: https://github.com/rberrelleza/byoc/blob/master/icon.png
    keywords:
    - app
    - container
    - docker
    maintainers:
    - email: rberrelleza@gmail.com
      name: Ramiro Berrelleza
    name: byoc
    type: application
    urls:
    - https://rberrelleza.github.io/byoc/byoc/byoc-0.1.0.tgz
    version: 0.1.0
generated: "2019-12-05T15:55:05.319343+01:00"
