apiVersion: v2
name: byoc
description: Deploy any container in Okteto
type: application
version: 0.1.0
icon: https://github.com/rberrelleza/byoc/blob/master/icon.png
keywords:
- app
- container
- docker
home: https://github.com/rberrelleza/byoc
maintainers:
- name: Ramiro Berrelleza
  email: rberrelleza@gmail.com
engine: gotpl

